#!/usr/bin/env bash
# Checks Holbertonschool file

LEFILE="holbertonschool"

if [ -e $LEFILE ]
then
    echo "holbertonschool file exists"
    if [ -s $LEFILE ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f $LEFILE ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi